sudo: required
services: 
  - docker

before_install:
  - docker build -t davycode/react-test -f Dockerfile.dev ./client

script:
  - docker run davycode/react-test npm run test -- --coverage

after_success:
  - docker build -t davycode/complex-docker-client ./client
  - docker build -t davycode/complex-docker-api ./server
  - docker build -t davycode/complex-docker-worker ./worker
  - docker build -t davycode/complex-docker-nginx ./nginx